# Generated by Django 2.2.16 on 2023-04-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20230411_1142'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='posts_follow_unique_follow',
        ),
    ]
